name: Build & Publish Report
on:
  schedule:
    - cron: "30 6 * * *"   # daily after the data refresh
  workflow_dispatch:

jobs:
  report:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: r-lib/actions/setup-r@v2

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rmarkdown
          needs: |
            rmarkdown
          cache-version: 1

      - name: Build report
        run: R -q -e 'source("scripts/make_report.R")'

      - name: Commit docs (if changed)
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add docs/index.html || true
          git diff --quiet && echo "No changes." || (git commit -m "docs: publish daily report" && git push)
