name: Build daily report

on:
  workflow_dispatch:
  schedule:
    - cron: '15 10 * * *'  # adjust time (UTC) as you like
  push:
    paths:
      - 'R/**'
      - 'scripts/**'
      - 'reports_daily.Rmd'
      - 'data/**'
      - '.github/workflows/daily-report.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      # Install system libraries required by CRAN packages
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libcurl4-openssl-dev \
            libjpeg-dev \
            libpoppler-cpp-dev \
            libx11-dev

      # Pandoc for rmarkdown/knitr
      - uses: r-lib/actions/setup-pandoc@v2

      # R + renv
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.5.0'

      - uses: r-lib/actions/setup-renv@v2
        with:
          # optional: speed up by pre-installing a few heavy packages
          cache-version: 1

      - name: Build report & outputs
        run: |
          Rscript -e 'source("scripts/update_all.R"); source("scripts/make_report.R")'

      - name: Commit docs & playsheet
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "CI: refresh data & docs"
          file_pattern: |
            docs/**
            outputs/playsheet*.csv
